build:
  image: node:12.9.1
  tags:
    - mac-runner
  when: manual
  script:
    - ./build-deps
    - shasum -a 256 ios/Libraries/* android/jni/libs/*/* > shasums.txt
    - cat shasums.txt
  artifacts:
    paths:
      - .
    expire_in: 1 week
