name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - name: Install build dependencies
        run: sudo apt-get install -y libncurses5
        if: matrix.os == 'ubuntu-latest'
      - name: Install build dependencies
        run: brew install automake libtool
        if: matrix.os == 'macos-latest'
      - name: Set yarn version
        run: yarn set version 1.19.1
      - name: Build packages
        run: yarn build